name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - master
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Replace environment variables
        run: |
          sed -i "s#url: 'STATICFORMS_URL'#url: '${{ secrets.STATICFORMS_URL }}'#g" src/environments/environment.ts
          sed -i "s#accessKey: 'STATICFORMS_ACCESSKEY'#accessKey: '${{ secrets.STATICFORMS_ACCESSKEY }}'#g" src/environments/environment.ts
          sed -i "s#submit: 'STATICFORMS_SUBMIT'#submit: '${{ secrets.STATICFORMS_SUBMIT }}'#g" src/environments/environment.ts
          sed -i "s#serviceId: 'EMAILJS_SERVICEID'#serviceId: '${{ secrets.EMAILJS_SERVICEID }}'#g" src/environments/environment.ts
          sed -i "s#templateId: 'EMAILJS_TEMPLATEID'#templateId: '${{ secrets.EMAILJS_TEMPLATEID }}'#g" src/environments/environment.ts
          sed -i "s#userId: 'EMAILJS_USERID'#userId: '${{ secrets.EMAILJS_USERID }}'#g" src/environments/environment.ts
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
